### ISSUE TITLE
read_bed can silently overwrites records

### ISSUE THREAD

**Issue by slazicoicr** [oicr-gsi/bamqc-legacy#12]
https://github.com/oicr-gsi/bamqc/blob/a3964603efc86334e3345d30c331c9aacab256b2/lib/GSI/bamqc.pm#L311-L315

This code adds a new BED record to the `bed` hash, using the BED chrom value as the key. This code assumes that the chrom value will always be unique. This assumption is broken in the BED example given in the [standard](https://genome.ucsc.edu/FAQ/FAQformat.html#format1)

```
chr22 1000 5000 cloneA 960 + 1000 5000 0 2 567,488, 0,3512
chr22 2000 6000 cloneB 900 - 2000 6000 0 2 433,399, 0,3601
```

**Comment by iainrb** [comment]
I think this may be OK. The `push` function appends an item to a list.

`%bed` is a hash of hashes of lists of hashes (!), so code like:

`push @{ $bed{intervals}{ $f[0] } }, $my_hashref;`

is appending `$my_hashref` to the array with reference denoted by `$bed{intervals}{ $f[0] }`.

The data structure is unnecessarily complicated and would almost certainly benefit from refactoring, but I don't think this is a bug as such.

**Comment by slazicoicr** [comment]
You are right (took a little of squinting and bracket counting).
